language: rust
notifications:
  webhooks: http://build.servo.org:54856/travis

rust:
  - stable
  - beta
  - nightly

cache: cargo
before_script:
  - (cargo install rustfmt || true)
  - export PATH=$HOME/.cargo/bin:$PATH
script:
  - cargo fmt -- --write-mode=diff
  - cargo build -v
  - cargo test -v
